# эти настройки не используются в testcontainers, нужны для применения миграций к локальной БД

changeLogFile="db/changelog/changelog-master.xml"

url=jdbc:postgresql://localhost:5432/postgres
username=postgres
password=postgres
driver=org.postgresql.Driver

liquibase.schemaName=public
liquibase.databaseChangeLogTableName=databasechangelog
liquibase.databaseChangeLogLockTableName=databasechangeloglock
